### ISSUE TITLE
[FO - Page de suivi] Créer la page de suivi auto-traitement

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#102]
Maquette [visible ici](https://xd.adobe.com/view/f7c127ce-f9de-4bf7-9b92-f799a3769859-a292/)

### Composition de la page
Titre : _Bonjour {prénom usager},_     
sous-titre: _Votre signalement {référence signalement}_

**Barre de progression avec 3 étapes :** 
- Signalement déposé : le signalement a été enregistré sur la plateforme
- Protocole envoyé : l'email protocole a été envoyé 
- Traitement terminé : l'email de suivi du traitement a été envoyé

**Boutons d'actions :** 
- Télécharger le protocole : 
   - Sur desktop : ouvre le pdf dans un nouvel onglet
   - Sur mobile : télécharge le pdf
- Trouver une entreprise labellisée -> ouverture modale de confirmation

**Accordéon "Info du signalement" :** 
- Référence du signalement
- Date de dépôt
- Infestation estimée : rappel du niveau donné à la fin du formulaire
- Protocole choisi : auto traitement

**Détails des événements :**     
Reprend dans l'ordre antéchronologique les événements sur le signalement.      
Pour l'auto-traitement, il s'agit uniquement de **messages automatiques**.

Les messages sont composés de : 
- Un label (facultatif) : 
- Une date
- Un titre
- Une description
- Un lien "en savoir plus" menant vers une modale ou une nouvelle page (facultatif)

| Message | Description | Label | Déclencheur | Action possible
| :--- | :--- | :--- | :--- | :---
| Signalement déposé | Votre signalement a bien été enregistré sur Stop Punaises. | Non | Signalement enregistré sur la plateforme | Non
| Protocole envoyé | Le protocole d'auto-traitement est disponible. | Non | L'email protocole a été envoyé | Télécharger le protocole -> Même comportement que le bouton
| Suivi du traitement | Votre problème de punaises est-il résolu ? | Label "Nouveau" tant que pas de réponse de l'usager | Email de suivi envoyé (45 jours après l'envoi du protocole) | En savoir plus -> ouverture page suivi
| Problème résolu | Vous avez résolu votre problème ! Merci d'avoir utilisé Stop Punaises. | Non | L'usager a confirmé ne plus avoir de problème | Non
| Signalement terminé | Votre avez mis fin à la procédure. Merci d'avoir utilisé Stop Punaises. | Non | L'usager arrête la procédure. | Non

**Comment by mathildepoulpux** [comment]
Quand je clique sur le bouton dans le mail, j'arrive à cette page, du coup je peux pas tester : 
![image](https://user-images.githubusercontent.com/97226289/207738327-da09a2cf-c127-4768-8026-4e07239d011c.png)

**Comment by emilschn** [comment]
Normalement corrigé en changeant les types de variables dans les templates lors du transfert.
