### ISSUE TITLE
[FO - Traitement pro] Accepter une estimation

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#114]
**User flow**
1. Accès à la page de suivi depuis le lien dans l'email
2. Clic sur le lien "En savoir plus" dans le message "Estimation [nom de l'entreprise]" de la page de suivi -> [voir ici](https://xd.adobe.com/view/f42d9963-8c39-4d0e-9305-d2781bbb7d15-a17e/)
3. Clic sur "Accepter" dans la modale -> [voir ici](https://xd.adobe.com/view/f42d9963-8c39-4d0e-9305-d2781bbb7d15-a17e/)

**Conséquences**
- FO : -> [voir ici](https://xd.adobe.com/view/f42d9963-8c39-4d0e-9305-d2781bbb7d15-a17e/screen/b0736dda-861b-4c6f-bd7e-10ca276f4b2f/)
    - Retour sur la page de suivi avec un Success message 
    - Le badge du message "Estimation [nom de l'entreprise]" est mis à jour dans le détail des événements de la page de suivi
    - Les autres estimations en cours sont marquées comme refusées (avec le badge "estimation refusée")
- BO: 
    - Les coordonnées de l'usager sont affichées pour l'entreprise
    - Envoi d'un email à l'entreprise pour l'informer qu'elle a été choisie
    - Une info "estimation acceptée" est ajoutée sur le listing des signalements à traiter de l'entreprise & de l'admin
    - Envoi d'un email aux autres entreprises pour les informer qu'une autre entreprise a été choisie
    - Le signalement est fermé pour les autres entreprises avec un motif "choix d'une autre entreprise"

Le parcours est dispo en [prototype ici](https://xd.adobe.com/view/f42d9963-8c39-4d0e-9305-d2781bbb7d15-a17e/)

**Comment by emilschn** [comment]
@mathildepoulpux pourquoi l'infestation est marquée comme résolue ?!

**Comment by mathildepoulpux** [comment]
Parce que c'est une erreur de copier / coller :D 
Je l'ai retiré !
