### ISSUE TITLE
[FO - Traitement pro] Problème non résolu - changement ou arrêt de procédure

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#117]
Il peut arriver que, malgré les interventions, le problème de punaise persiste.
L'usager peut l'indiquer via l'email de feedback est envoyé aux usagers après une période.
L'email est envoyé 30 jours après que le signalement a été marqué comme traité par l'entreprise intervenante.

**User flow**
1. Accès à la page de suivi depuis le lien dans l'email
2. Clic sur le lien "En savoir plus" dans le message "suivi du traitement" de la page de suivi
3. Clic sur "J'ai toujours des punaises"
4. Accès à une seconde page avec 3 choix : 
    - 4. a Trouver une autre entreprise
    - 4. b Passer à l'auto-traitement
    - 4. c Arrêter la procédure

**Conséquences 4. a Trouver une entreprise**
- FO :
    - Page de suivi "à traiter" à la première étape avec un Success message 
    - Message d'info "Nouvelle procédure" est ajouté dans le détail des événements de la page de suivi
- BO: 
    - Le signalement passe en "nouveau" pour les entreprises qui peuvent envoyer des estimations / prendre contact

**Conséquences 4. b Passer à l'auto-traitement**
- FO : 
    - Page de suivi "auto-traitement" à la première étape avec un Success message 
    - Message d'info "Signalement transféré" est ajouté dans le détail des événements de la page de suivi
- BO: 
    - Le signalement passe en "auto-traitement" pour l'admin
    - Le signalement est fermé pour l'entreprise intervenante avec le motif "arrêt usager"
    - L'infestation est marqué comme non résolue pour l'entreprise

**Conséquences 4. c Arrêter la procédure**
- FO: 
    - Retour sur la page de suivi avec un Success message 
    - Message d'info "Signalement terminé" est ajouté dans le détail des événements de la page de suivi
    - Les boutons "télécharger le protocole" et "trouver une entreprise" sont masqués sur la page de suivi
    - Le lien "en savoir plus" est masqué dans le message "suivi du traitement" de la page de suivi
- BO: 
    - Le signalement passe en statut "fermé" pour l'admin et l'entreprise avec le motif "arrêt usager"
    - L'infestation est notée comme non résolue

**Comment by emilschn** [comment]
@mathildepoulpux 
Pour le cas 4a, ça veut dire qu'on remet à zero d'éventuelles estimations précédentes, on supprime les discussions passées ? 
Sauf avec l'entreprise qui a fait l'intervention ?

**Comment by emilschn** [comment]
Vu ensemble avec Arnaud : le cas 4a se charge uniquement d'envoyer une notification à l'admin pour prise en charge manuelle.
Les éléments automatisés seront vus plus tard.
