### ISSUE TITLE
[Emails usagers] Créer les emails suite aux actions

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#119]
Liste des emails : 
- [x] Nouvelle estimation
- [x] Nouveau message
- [x] Traitement effectué
- [x] Suivi post-traitement
- [x] Suivi auto-traitement
- [x] Aucune entreprise dispo

[Le template](https://my.sendinblue.com/camp/template/38/message-setup) est le même pour tous : l'email avec le bouton vers la page de suivi

## Nouvelle estimation
Déclencheur : Une entreprise envoie une estimation

_Objet :_
Stop Punaises : nouvelle estimation pour votre signalement !

_Contenu :_
Stop Punaises : nouvelle estimation

Bonjour {prenom usager}

L'entreprise {nom entreprise} vous a envoyé une estimation pour votre signalement {reference}.
Cliquez sur le bouton ci-dessus pour la consulter puis l'accepter ou la refuser.

_bouton :_ Consulter l'estimation

Attention : il s'agit d'une estimation, le prix peut varier.

## Nouveau message
Déclencheur : Une entreprise envoie un message à l'usager

_Objet :_
Stop Punaises : un nouveau message vous attend !

_Contenu :_
Stop Punaises : nouveau message

Bonjour {prenom usager}

L'entreprise {nom entreprise} vous a envoyé un message.
Cliquez sur le bouton ci-dessus pour le lire et y répondre.

_bouton :_ Voir le message

## Traitement effectué
Déclencheur : L'entreprise a marqué l'intervention comme terminée

_Objet :_
Stop Punaises : infestation traitée

_Contenu :_
Stop Punaises : infestation traitée

Bonjour {prenom usager}

L'entreprise {nom entreprise} a marqué votre infestation comme traitée.
Dans un mois, nous vous adresserons un email pour nous assurez que votre problème est bien résolu.

_bouton :_ Accéder au suivi

## Suivi auto-traitement
Déclencheur : 30 jours après que le signalement a été marqué comme "terminé"

_Objet :_
Stop Punaises : votre problème est-t-il résolu ?

_Contenu :_
Stop Punaises : votre problème est-il résolu ?

Bonjour {prenom usager}

Nous vous avons envoyé un protocole d'auto-traitement le {date}.
Votre problème de punaises est-il bien résolu ? 
Cliquez sur le bouton ci-dessous pour effectuer votre suivi.

_bouton :_ Accéder au suivi

## Suivi post-traitement
Déclencheur : 45 jours après envoi de l'auto-traitement

_Objet :_
Stop Punaises : votre problème est-t-il résolu ?

_Contenu :_
Stop Punaises : votre problème est-il résolu ?

Bonjour {prenom usager}

L'entreprise {nom entreprise} a traité votre infestation il y a un mois.
Votre problème de punaises est-il bien résolu ? 
Cliquez sur le bouton ci-dessous pour effectuer votre suivi.

_bouton :_ Accéder au suivi

## Aucune entreprise dispo
Déclencheur : Toutes les entreprises ont refusé le signalement

_Objet :_
Stop Punaises : du nouveau sur votre signalement

_Contenu :_
Stop Punaises : mise à jour de votre signalement

Bonjour {prenom usager}

Nos entreprises ne sont malheureusement pas en capacité de traiter votre demande.
Cliquez sur le bouton pour découvrir vos options.

_bouton :_ Accéder au suivi

**Comment by emilschn** [comment]
@mathildepoulpux  je crois qu'il faudra changer le texte du mail "nouveau message"

**Comment by mathildepoulpux** [comment]
exact, c'est modifié
