### ISSUE TITLE
[FO] - Crédits Visuels

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#176]
Crédits photos pour les illustrations animés / infographies ( officielles ) : Citizen

**Comment by mathildepoulpux** [comment]
Ajouter "Crédit : Citizen" en légende des infographies "Punaises de lit où se cachent-elles" et "Punaises de lit : comment les éviter" sur la page info : https://stop-punaises.beta.gouv.fr/information 

Modifié aussi sur les pdf en téléchargement : https://drive.google.com/drive/u/0/folders/1kyFwKVDLbqQbL_kdRj1YHxGyqhQNXdix
