### ISSUE TITLE
[FO] - Vidéo

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#177]
Modification de la vidéo Canapé qui parle par Video Animée officielle du MTE
Source à venir 
Crédits à mentionner : Citizen

**Comment by arnaudchouk** [comment]
video dispo ici : https://drive.google.com/file/d/1FyVLbu8IG0_XLd7BSO9EmsKfWEvMq6BK/view?usp=share_link

**Comment by mathildepoulpux** [comment]
Mettre la vidéo sur la homepage en remplacement de celle qui a été supprimée avec en légende "Crédit vidéo : Citizen" 
![image](https://user-images.githubusercontent.com/97226289/208635782-5becd923-cd36-4bf4-ba4a-fbb3f9c330d0.png)

**Comment by emilschn** [comment]
On met quoi comme vidéo sur la page "Informations" ? @mathildepoulpux @arnaudchouk

**Comment by mathildepoulpux** [comment]
La même ? 
Il n'y a plus que celle là de toute façon
