### ISSUE TITLE
[FO] - Intégration Photos

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#178]
Phototeque :
https://www.inelp.fr/phototheque/
@mathildepoulpux on avait discuté d'intégrer dans les modales d info, on a pas mal de choix  pour le coup :/

faire figurer la formule : "crédit photo : INELP sous chaque photo

**Comment by mathildepoulpux** [comment]
Les photos sont dispo sur le drive : https://drive.google.com/drive/u/0/folders/1JgucWNHiiEWaVaC-o-9VP0eLVAIMa6gE 
**⚠️ les légendes de chaque photo (celles qui décrivent l'image) sont également à ajouter en balise alt**

----

### Sur la page info : 
![image](https://user-images.githubusercontent.com/97226289/208636139-5c6c8236-ec65-4cc6-83e1-9d6b471d7449.png)

Dans la partie "Les signes à la maison", ajouter les photos : 
- dejections-punaise-sommier.jpg -> légende "Déjections et œufs de punaises de lit sur un sommier"
- traces-punaises-de-lit-couture-matelas.jpg -> légende "Traces de punaises de lit dans la couture d'un matelas"
- punaises-infestation-massive-oeufs-mues.jpg -> légende "Infestation massive avec punaises de lit à différents stades de croissance,  œufs et mues"
--> Sur la ligne dessous des photos  ajouter "Crédit photo : INELP"

Dans la partie "Les signes sur la peau" : 
- piqures-punaises-de-lit-bras.jpg -> légende "Piqures de punaises en ligne sur un bras"
- piqures-punaises-de-lit-cou.jpg -> légende "Piqures de punaises groupées dans le cou"
--> Sur la ligne dessous des photos  ajouter "Crédit photo : INELP"

----

### Dans "Comment reconnaître les punaises de lit"
Remplacer la photo de punaise par la photo "punaise-de-lit-gros-plan.jpg" avec la légende "Gros plan d'une punaise de lit - Crédit photo : INELP"

![image](https://user-images.githubusercontent.com/97226289/208639381-4ac0f5aa-5c49-4d21-84db-4506adb11b66.png)

----

### Modale piqures
ajouter les photos : 
- piqures-punaises-de-lit-bras.jpg -> légende "Piqures de punaises en ligne sur un bras"
- piqures-punaises-de-lit-cou.jpg -> légende "Piqures de punaises groupées dans le cou"

Sur la ligne dessous des photos  ajouter "Crédit photo : INELP"

![image](https://user-images.githubusercontent.com/97226289/208640255-f825f802-8bbb-44cc-b28a-782ef3b636ad.png)

----

### Modale déjections
ajouter les photos : 
- dejections-punaise-sommier.jpg -> légende "Déjections et œufs de punaises de lit sur un sommier"
- dejections-punaise-matelas.jpg -> légende "Déjections de punaises de lit dans la couture d'un matelas"

Sur la ligne dessous des photos  ajouter "Crédit photo : INELP"

![image](https://user-images.githubusercontent.com/97226289/208640451-794fed92-1dc4-49c3-a900-2b321cf970c9.png)

----

### Modale oeufs et larves
ajouter les photos : 
- oeufs-punaises-sommier.jpg -> légende "Déjections et œufs de punaises sur un sommier"
- punaise-infestation-massive-oeufs-mues.jpg -> légende "Infestation massive avec punaises de lit à différents stades de croissance,  œufs et mues"

Sur la ligne dessous des photos  ajouter "Crédit photo : INELP"

![image](https://user-images.githubusercontent.com/97226289/208642161-6a49f6ff-a383-44a1-ad79-714e19c77670.png)

---- 

Modale punaise de lit
ajouter les photos : 
- punaise-de-lit-gros-plan.jpg -> la légende "Gros plan d'une punaise de lit"
- punaises-lit-adultes-matelas.jpg -> légende "Punaises de lit adulte sur un matelas"

Sur la ligne dessous des photos  ajouter "Crédit photo : INELP"

![image](https://user-images.githubusercontent.com/97226289/208642070-7c3fdee5-715a-481a-965f-9110f70b0138.png)
