### ISSUE TITLE
[Email - auto-traitement] Ajouter lien vers page de suivi

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#185]
1. Je suis un usager
2. Je dépose mon signalement
3. Je choisis l'option auto-traitement
4. Je reçois un email
5. Je clique sur le bouton dans l'email
6. Le PDF d'instruction s'ouvre 

Dans la mesure où on a une page de suivi pour l'auto-traitement, je pense qu'il faudrait changer le lien dans l'email pour renvoyer vers la page de suivi plutôt que de télécharger directement le pdf.
Ca permet de déjà habituer l'usager à la page de suivi (vu qu'il va y revenir 45j après).

Vous en pensez quoi @arnaudchouk @emilschn ?

![image](https://user-images.githubusercontent.com/97226289/208660206-ac12a20a-18aa-4a2e-8d93-43727e0af7ce.png)

**Comment by arnaudchouk** [comment]
l idee est bonne mais dans la pratique, il faut je pense que tu puisses avoir vite le doc entre les mains
du coup tu veux orienter sur la page de suivi pour qu il telecharge le doc?

**Comment by mathildepoulpux** [comment]
Oui c'était ma question

**Comment by mathildepoulpux** [comment]
Décision : on remplace le lien vers le PDF dans l'email par le lien vers la page de suivi
