### ISSUE TITLE
[FO - Email - Traitement effectué] Email non reçu

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#196]
L'entreprise a marqué le traitement comme effectué pour mon signalement
Je n'ai pas reçu l'email que je devrais recevoir 
cf. #119 

----
#### Traitement effectué
Déclencheur : L'entreprise a marqué l'intervention comme terminée

_Objet :_
Stop Punaises : infestation traitée

_Contenu :_
Stop Punaises : infestation traitée

Bonjour {prenom usager}

L'entreprise {nom entreprise} a marqué votre infestation comme traitée.
Dans un mois, nous vous adresserons un email pour nous assurez que votre problème est bien résolu.

_bouton :_ Accéder au suivi

**Comment by sfinx13** [comment]
Pas reproductible

![Image](https://user-images.githubusercontent.com/5757116/209201236-e7e7fa72-75cd-4815-b97c-2efacf0ba40a.png)
