### ISSUE TITLE
[BO - Tableau de bord entreprise] Compteur pas à jour

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#197]
Sur le tableau de bord entreprise
J'ai 0 signalement nouveau
![image](https://user-images.githubusercontent.com/97226289/208890149-aac4aae8-d1e3-4787-9375-3e30b06fc906.png)

Sauf qu'il y en a un 
![image](https://user-images.githubusercontent.com/97226289/208890219-30eb4ae3-3920-4292-acaa-a2714dd0fc20.png)

Il faudrait que le compteur sur le tableau de bord soit à jour

**Comment by emilschn** [comment]
@mathildepoulpux je ne reproduits pas ; tu pourrais me donner un exemple ?

**Comment by mathildepoulpux** [comment]
Je reproduis pas non plus 🤷‍♀ 
Je ferme le ticket, je le rouvrirai si ça se reproduit

**Comment by mathildepoulpux** [comment]
Ah bah je viens de reproduire
Je suis connecté en tant qu'entreprise sur le compte company-punaises-04@yopmail.com
Sur mon tableau de bord j'ai : 


![Image](https://user-images.githubusercontent.com/97226289/210056993-a367cb3c-aeed-4e9a-aaed-b9080270eff7.png)


Alors que dans mon listing : 



![Image](https://user-images.githubusercontent.com/97226289/210057017-ad1b2d04-2af8-4730-a46b-9e675a930c90.png)
