### ISSUE TITLE
[Email - traitement pro - problème résolu] Email non envoyé

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#199]
Je suis un usager
J'ai choisi le traitement pro
Mon signalement a été marqué comme traité
A J+30 je dois recevoir un email
L'email n'est pas envoyé

**Comment by sfinx13** [comment]
![Image](https://user-images.githubusercontent.com/5757116/208897245-6460853b-9340-4949-8f73-b2150141aa23.png)
