### ISSUE TITLE
[BO - Email] Erreur sur le lien nouveau signalement

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#200]
Je suis une entreprise
Un nouveau signalement est dispo sur mon territoire
Je clique dans l'email sur le lien
J'arrive à une page d'erreur

Le lien dans l'email : http://stop-punaises-staging.osc-fr1.scalingo.io/bo/signalements/2544a531-863f-4083-8f89-f9184217f2e8

![image](https://user-images.githubusercontent.com/97226289/208901514-b670a9dc-375b-41cc-8bdb-f8a46b9cd830.png)

**Comment by sfinx13** [comment]
Pas reproductible sur staging. je le rremet sur la colonne test
