### ISSUE TITLE
Un signalement hors-périmètre a pu passer en Pro

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/stop-punaises#236]
Exemple : 2023-335

**Comment by arnaudchouk** [comment]
sur le signalement 2023 -42 - hors perimetre - 
la demande a pu passer en Pro après la réception de l auto traitement >> mais le service pro n est pas encore proposé sur ce departement
ce signalement n apparait cependant pas pour les entreprises du 13 + il n'est pas listé en "hors perimetre"
