### ISSUE TITLE
[FO - Activation de compte] Mise à jour du message d'erreur lorsqu'un compte est deja activé

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/stop-punaises#241]
![image](https://user-images.githubusercontent.com/5757116/210787375-c7cabefc-0bf1-4a06-a430-4ffd2a176624.png)

Proposition de message (type: avertissement au lieu erreur) dans ce cas d'usage :
```
Votre compte est déjà activé, si vous avez oublié votre mot de passe, veuillez le réinitialiser [link].
```

**Comment by emilschn** [comment]
@sfinx13 a priori, tu as déjà prévu cette erreur : il y a une classe d'exception UserAccountAlreadyActiveException
Tu penses qu'elle ne fonctionne pas ?

**Comment by sfinx13** [comment]
oui exact et je me suis trompé de screenshot c'est plutôt celui ci, en fait il faut compléter ce message 
![image](https://user-images.githubusercontent.com/5757116/220142724-e76ee7ff-abb0-4687-bc0f-e56918df43fa.png)

...... si vous avez oublié votre mot de passe, veuillez le réinitialiser [link].
