### ISSUE TITLE
[FO-Signalement] Logement social

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#247]
La loi oblige les bailleurs sociaux à traiter le problème de punaises - on ne peut donc pas laisser un usager solliciter directement une entreprise 3d 
Avant de les intégrer pleinement à la plateforme, il faut qu'on limite la transmission des signalements pour les logements sociaux, tout en enregistrant la donnée dans la base

Proposition
Lorsqu'un occupant indique qu'il est dans un logement social sur le formulaire 2 (avec ou sans allocation)
![image](https://user-images.githubusercontent.com/93710194/211841947-b75e0dd0-6d67-4f24-ade4-d553c658c50d.png)

on sauvegarde l'adresse en base sans détail sur le niveau de l infestation au clic sur le bouton suivant > on peut l'intégrer au listing hors perimetre dans un 1er temps

Puis on affiche une page similaire à celle qui s'affiche lorsque l usager est hors périmetre, mais avec un texte spécifique (voir ci dessous)
![image](https://user-images.githubusercontent.com/93710194/211842397-b5603753-b5e5-4a75-9dff-06654c7da049.png)

Texte à intégrer: 
En tant que locataire du parc social votre bailleur doit avoir un service de gestion des nuisibles et punaises de lit.
Ceux-ci n’étant pas encore connectés à la plateforme, nous vous invitons à contacter sans plus attendre votre bailleur pour lui signifier votre problème et lui demander d’intervenir dans les meilleurs délais
Vous pouvez également renseigner vos coordonnées pour recevoir le protocole d’auto-traitement par mail qui facilitera l’intervention de votre bailleur et limitera la diffusion du problème"

**Comment by emilschn** [comment]
Pour ce qui est de l'interface front, c'est ok, pas de soucis.

Pour l'enregistrement, je pense qu'il faut qu'on se serve de la donnée bailleur social pour ne pas l'afficher aux entreprises, mais pour l'afficher aux admin (plutôt traiter comme auto-traitement, du coup).
Il faudra juste intégrer cette donnée dans la liste.

Est-ce que ce serait ok ?  @arnaudchouk @mathildepoulpux

**Comment by arnaudchouk** [comment]
pour moi c est ok - 
il faudrait meme peut etre prevoir - mais ce sera peut etre dans un second temps - de leur envoyer egalement l email de suivi apres x jours - ca permettrait de voir si les bailleurs font leur taf

**Comment by emilschn** [comment]
Vu qu'on se rapproche du fonctionnement actuel d'auto-traitement, ils vont le recevoir, du coup :)

**Comment by arnaudchouk** [comment]
parfait pour moi

**Comment by mathildepoulpux** [comment]
Du coup on ajoute un type de signalement "parc social" (avec A traiter / auto-traitement) ?
Ca permettrait de les filtrer pour l'admin

**Comment by emilschn** [comment]
J'ai mis "Logement social" dans cette colonne, mais on peut mettre "Parc social" si tu penses que c'est mieux.

**Comment by mathildepoulpux** [comment]
Ah peu importe, les 2 vont :)
