### ISSUE TITLE
[Bo Signalement] Liste Evenements

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#250]
Quand je rentre dans n'importe quel signalement, qu il soit accepté ou non, et que j'y ai répondu ou non je vois une liste d'évènements qui correspond aux actions des autres entreprises
![image](https://user-images.githubusercontent.com/93710194/212100816-4829a2dc-3b7a-4fc2-965a-63a9681744d6.png)

je vois meme que des devis ont été refusé - 
![image](https://user-images.githubusercontent.com/93710194/212100942-048eb186-420b-401a-ba79-e3f1f1dc0ec9.png)

Les evenements listés ne doivent concernés que les actions de l entreprise + les cas où l'usager fait une action qui a une conséquence pour mon entreprise

**Comment by arnaudchouk** [comment]
je me connecte en tant qu entreprises punaises - [punaises@yopmail.om
quand je vais voir les signalements recus, je vois sur le fil evenement de mon entreprise, l'evenement "annulation intervention" d autres entreprises... (je crois que c est le seul qui apparait)
![image](https://github.com/MTES-MCT/stop-punaises/assets/93710194/80c75de6-427b-4f22-aba1-b89894132a71)

**Comment by emilschn** [comment]
Vu ensemble : on garde les événements, mais on anonymise le nom de l'entreprise pour les autres entreprises
