### ISSUE TITLE
[BO - Signalement] A Cloturer 2023-14/16/19/20/22/28

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/stop-punaises#269]

**Comment by emilschn** [comment]
Ca veut dire qu'il faudrait une fonction admin de cloture de signalements assez rapidement @mathildepoulpux @arnaudchouk  ?
En attendant, c'est juste les cloturer en BDD ?

**Comment by arnaudchouk** [comment]
effectivement je pense que ce ne serait pas inutile - là vu le volume ca va mais avec plus de territoires et de com ce sera effectivement plus simple

**Comment by mathildepoulpux** [comment]
Oui, on peut se baser sur le #57

**Comment by emilschn** [comment]
C'est clôturé pour ceux-ci !
