### ISSUE TITLE
[BO Signalement] Signalement Hors territoire peut passer à signalement pro

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#280]
Voir signalement suivant
https://stop-punaises.beta.gouv.fr/bo/signalements/22c96c66-a006-48e9-bea7-a8de11cb2bd8

**Comment by arnaudchouk** [comment]
@emilschn  les signalements 272 , 271, le 266 sont deposes sur pages traitement pro (pour le role admin) alors qu ils sont hors departement
A priori la page suivi permet de demander le traitement pro toujours

**Comment by emilschn** [comment]
Et bien je viens de découvrir qu'en base de données, on avait récupéré les territoires actifs d'histologe (à une date indéfinie).
Donc il y avait bien une obligation dans le parcours de signalement pour que ce soit juste le 13 qui soit actif.
Mais dans le TB, le tri était mal fait.
A priori, ça n'a pas d'autre incidence que l'affichage dans le TB et la possibilité de demander un traitement pro.
C'est corrigé, en tout cas.
