### ISSUE TITLE
[Signalement] Je peux basculer sur une demande pro après un auto traitement en étant hors du territoire

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#290]
le mail de protocole auto traitement reçu, suite au renseignement d'un CP hors territoire,  envoie sur page de suivi, sur laquelle on me propose de faire appel à une entreprise labellisée
ce bouton et cette possibilité ne doivent pas exister

**Comment by emilschn** [comment]
C'est un doublon de ça, non : https://github.com/MTES-MCT/stop-punaises/issues/280 ? @arnaudchouk

**Comment by arnaudchouk** [comment]
exact désolé -
