### ISSUE TITLE
[Mails de suivi - Autotraitement] Utiliser template #4	Suivi auto-traitement

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#307]
le mail de suivi envoye apres protocole auto traitement semble etre le template 

#3 | Suivi post-traitement
Mais il doit etre envoye qu au suivi intervention entreprise

Remplacer par le template #4 suivi auto traitement
et renvoyer à tous les destinataires du mauvais mail de suivi

**Comment by mathildepoulpux** [comment]
Quand j'ai spécifié les emails, j'ai inversé les deux templates [dans les specs](https://github.com/MTES-MCT/stop-punaises/issues/119) (c'est corrigé maintenant)
-> Je pense qu'on envoie du coup l'email suivi post-traitement au lieu du suivi auto-traitement, il faut les inverser :)
