### ISSUE TITLE
[BO - Signalement] Traitement en cours

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#308]
Permettre à l'entreprise sélectionnée de Fermer le signalement sans déclarer comme traité (seul bouton aujourd'hui)
il arrive que des usagers ne donnent pas suite aux appels pour prise de rdv et ne reviennent pas sur la plateforme.
Il faut qu une entreprise puisse fermer le signalement pour non intervention
une fois le clic fait envoyer un mail à l'usager pour lui demander s'il souhaite poursuivre la procédure ou clôturer le signalement
Si clôture > ferme le signalement pour tous
Si poursuite > réouvrir signalement aupres des entreprises pour choix d une autre estimation

@mathildepoulpux t en penses quoi ?

**Comment by mathildepoulpux** [comment]
Oui, faut voir à quel moment on donne la possibilité de l'action : 
- Dès que l'entreprise accepte le signalement ?
- Après l'envoi d'une estimation ?
- Après un certain délai ?

Pour l'admin, il faudrait que l'option soit dispo tout le temps

**Comment by arnaudchouk** [comment]
je dirais, 
* après avoir envoyé un message ou une estimation

**Comment by arnaudchouk** [comment]
ca a l air d etre ca le workflow effectivement : 
si l'usager veut recommencer
    on rouvre les estimations des autres entreprises si il y en avait
        doit-on prévenir les entreprises ? celles qui avaient déjà fait un estimation ? celles qui n'en avaient pas fait ?
        > si l entreprise avait fait une estim pas utile de l alerter, s il est finalement selectionne ou contacte par l usager il sera notifie
        > s il n a pas fait d estim à l'époque, on peut rebasculer sur nouveau ? (pas sur de ce flow là)
        
    l'usager se retrouve de nouveau face à la liste des estimations
        celle de l'entreprise qui a clôturé est marqué "annulée" ou autre ? 
        Annulée ca me parait bien

Concernant la fermeture par l admin, ca ferme tout - est ce qu on envoie un des mails déjà présents à la clôture ?

**Comment by mathildepoulpux** [comment]
Signalement clôturé
Déclencheur : L'entreprise a clôturé un signalement après que son estimation a été acceptée

Objet :
Stop Punaises : l'entreprise {nom entreprise} souhaite clôturer votre signalement

Contenu :
Stop Punaises : clôture de votre signalement

Bonjour {prenom usager}

L'entreprise {nom entreprise} souhaite clôturer votre signalement.
Cliquez sur le bouton suivant pour confirmer la clôture du signalement ou chercher une nouvelle entreprise !

bouton : Accéder au suivi

**Comment by emilschn** [comment]
**Mise à jour de mon message ci-dessus avec les commentaires d'Arnaud**

1/ L'admin a une action "fermer le signalement" activable à tout moment

- envoyer un mail à la clôture

2/ Un pro peut renoncer à son intervention après avoir envoyé une estimation

- si l'estimation n'a pas encore été acceptée
    - on annule juste l'estimation
- si l'estimation a déjà été acceptée
     - on envoie le mail proposé par Arnaud (dans ce cas, prévoir template @mathildepoulpux)
    - si l'usager décide de clôturer
       -  on ferme
    - si l'usager veut recommencer
       -  on rouvre les estimations des autres entreprises si il y en avait
       -  passer en "Nouveau" pour les entreprises qui n'ont pas fait d'estimation
       -  l'usager se retrouve de nouveau face à la liste des estimations
           -  celle de l'entreprise qui a clôturé est marqué "annulée"

**Comment by arnaudchouk** [comment]
ca a l air ok -
juste le nom du bouton est peu engageant et met la responsabilite sur l entreprise
plutot basiquement cloturer le signalement
de meme le texte du mail recu en cas de cloture par l entreprise est différent du texte de mathilde

L'entreprise Ramos **souhaite renoncer à son intervention**.

Conserver souhaite clôturer

**Comment by arnaudchouk** [comment]
A priori on a une régression
Lorsqu une entreprise envoie une estimation ou un message à un usager, il ne peut rien faire tant que l'usager ne le sélectionne pas

Le bouton n est plus affiché en haut de l ecran
![Image](https://github.com/MTES-MCT/stop-punaises/assets/93710194/723a94cc-7cdb-4f1e-866c-2ef6b678b27e)
