### ISSUE TITLE
[BO - Suivi] Si un administrateur ferme un signalement, le rendre inaccessible à l'usager

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#331]
si un signalement est fermé par administrateur
usager recoit mail de suivi permettant de soumettre de nouveau sa demande aux entreprises
mais le signalement reste fermé, donc non visible ni reçu par entreprise
2023-316

**Comment by emilschn** [comment]
18/03 : Le signalement a été créé en auto-traitement
03/05 : Envoi du mail de suivi d'auto-traitement
01/06 : Fermeture par l'administrateur
14/06 : Passage en traitement pro

Lorsque l'administrateur ferme un signalement, les entreprises sont prévenues mais pas les usagers.

Ca veut dire que l'usager a sûrement utilisé le lien du mail du 03/05 qui n'était pas caduc.

@arnaudchouk Je vois plusieurs solutions
1/ On souhaite que l'usager puisse revenir sur sa décision, même si c'est l'admin qui a fermé le signalement.
Dans ce cas, on rouvre le signalement avant de suivre la procédure de passage en pro classique

2/ On se dit que la personne a été trop longue et qu'elle n'a qu'à refaire un signalement de zero, puisque la situation a probablement changé entre temps.
Dans ce cas, au moment de la fermeture par l'administrateur, on désactive le lien de suivi de signalement précédent

Plutôt solution 1 ?

**Comment by arnaudchouk** [comment]
plutôt option 2
si l admin ferme c est qu il y a plus de 3 mois qu il a fait le protocole
les entreprises le disent, si le client ne revient pas apres quelques jours c est qu il a trouve ailleurs
