### ISSUE TITLE
[Signalement Hors Zone] Afficher liste entreprise

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#352]
Modification du service en cas de signalement Hors zone : 
* Un usager saisi un code postal hors zone ouverte
* La page suivante s'affiche avec texte modifié : 
" Renseignez vos coordonnées pour accéder à la liste des entreprises labellisées de votre département et recevoir le protocole de préparation et d'auto traitement par e-mail.
Vous pouvez également le service "Info logement indigne" au 0806 706 806 (prix d'un appel local)"
* Modifier le bouton : Afficher la liste des entreprises
*Au clic, Envoi mail + Afficher page entreprise :
![Image](https://github.com/MTES-MCT/stop-punaises/assets/93710194/6db191e8-7f35-48a1-9903-8ca2b9794cc5)
 * ordre affichage entreprises : random à chaque chargement de la page
 
* fichier source entreprises : https://docs.google.com/spreadsheets/d/1Bqy89j_sFnftJdyAal04nfo2czMvOt8e/edit?usp=drive_link&ouid=103115680612514741617&rtpof=true&sd=true

**Comment by arnaudchouk** [comment]
complement :
est ce qu on peut prevoir dans le mail envoyé d integrer un lien renvoyant vers la page des entreprises labellisées du departement aussi ?

**Comment by emilschn** [comment]
Fichier à importer :

[entreprises.csv](https://github.com/MTES-MCT/stop-punaises/files/12783638/entreprises.csv)
