### ISSUE TITLE
[Signalement Hors Zone] Texte page coordonnée

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#354]
une coquille s'est glissée dans le texte
Remplacer :
* Renseignez vos coordonnées pour accéder à la liste des entreprises labellisées de votre département et **recevoir le protocole de préparation d'auto-traitement par e-mail.** 
Par : 
* Renseignez vos coordonnées pour accéder à la liste des entreprises labellisées de votre département et recevoir le protocole de préparation et d'auto traitement par e-mail.

**Comment by emilschn** [comment]
si c'était juste le "et" manquant, c'est corrigé (si il y a autre chose, signale-moi)
