### ISSUE TITLE
[Signalements Hors Zone] Departement manquant

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#355]
test avec departement 63000
ancien flow s affiche
![image](https://github.com/MTES-MCT/stop-punaises/assets/93710194/70acdcef-4925-4434-b9f2-ebfce2b0c36f)

meme resultat avec 23000, 23001

je n ai pas testé tous les departements mais certains ont le bon flow pas d autres

**Comment by emilschn** [comment]
tu n'es pas sur la bonne URL d'après ta barre d'adresse
il est possible que les mails (ou autre raison) te redirige vers la staging (qui n'est pas la même que le lien que je t'ai transmis)
c'est pour ça que tu n'as pas le bon fonctionnement ici

**Comment by arnaudchouk** [comment]
ok 
mais si je leur envoie le site ils vont avoir le meme bug du coup ?
