### ISSUE TITLE
[Signalement zone ouverte] Estimation pas accessible

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#357]
signalement 2023-11
https://stop-punaises-staging.osc-fr1.scalingo.io/signalements/651e847f20e33#

je clique dans le lien mail, je clic sur en savoir plus, rien ne s affiche
par contre les echanges usagers pas de probleme

**Comment by emilschn** [comment]
Mauvais lien de plateforme (celui de la staging)
Test à refaire avec la bonne plateforme (je laisse ouvert, parce que ça ne concerne pas ce que j'ai modifié, donc c'est possiblement un bug quand même)

**Comment by emilschn** [comment]
retesté avec le déploiement, pas de soucis
