### ISSUE TITLE
[Email usagers]Liens non fonctionnels

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#358]
quelques mails ont un lien fonctionnel, pas d autres
parc social, lien pour recuperer protocole ne marche pas 
https://stop-punaises-staging.osc-fr1.scalingo.io/signalements/651e861fd8d91

la c est un signalement sur territoire ouvert
https://stop-punaises-staging.osc-fr1.scalingo.io/signalements/651e861fd8d91

mais d autres ont fonctionné
https://stop-punaises-staging.osc-fr1.scalingo.io/signalements/651e847f20e33

**Comment by emilschn** [comment]
Lien vers mauvaises plateforme (je laisse ouvert pour regarder)

**Comment by emilschn** [comment]
Ok, c'est ajusté
