### ISSUE TITLE
[Signalement Parc Public] Lien Protocole Erreur

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#359]
Test sur un signalement zone experimentation ouverte - Marseille
parc social - donc redirection vers protocole
![image](https://github.com/MTES-MCT/stop-punaises/assets/93710194/c2aeb530-ef45-44d8-8f2f-ccbcd3df9586)

mail  recu mais lien vers page erreur
![image](https://github.com/MTES-MCT/stop-punaises/assets/93710194/bc907fbd-4fac-4ab5-9150-ab3967677b37)

signalement bien depose
![image](https://github.com/MTES-MCT/stop-punaises/assets/93710194/b1e2ff6d-d950-4371-9f82-c0b65d04eead)

**Comment by arnaudchouk** [comment]
si je ne suis pas parc public, sur departement ouvert et que je demande auto traitement : le lien fonctionne

**Comment by emilschn** [comment]
Ok, c'est corrigé !
