### ISSUE TITLE
[Annuaire entreprises] Les entreprises n'apparaissent pas pour les DOM

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#366]
une entreprise apparait dans la liste annuaire avec le code 974 (
974 | EDEN VERT 3D | 79 rue Marius et Ary Leblond 97460 Saint-Paul | https://edenvert3d.fr/boutiques/eden-vert-3d-la-reunion-974.html

mais pas sur le site avec le code postal d'un de ces territoires
![image](https://github.com/MTES-MCT/stop-punaises/assets/93710194/ceef700f-ff7d-4be8-9bfc-382ad6fea52f)

**Comment by mathildepoulpux** [comment]
Je viens de faire le test sur staging et idem
J'ai le message `Aucune entreprise n'est disponible dans votre département.` alors qu'il y en a 7 référencées

**Comment by mathildepoulpux** [comment]
Après tests sur la prod : ça fonctionne pas uniquement pour les DOM (971, 972, 973, 974) à mon avis c'est parce qu'on prend en compte que les 2 premiers chiffres donc on cherche le département 97 (qui n'existe pas)
