### ISSUE TITLE
Ajouter la partie pour les ERP et les transports

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#370]
Tâches UX:
- [x] Specs formulaire
- [x] Specs BO
- [x] Modèle email
- [x] [Maquette form](https://xd.adobe.com/view/cd89c517-038e-41f2-a80f-dfa7f5be7df5-98da/)
- [x] PDF "conseils pour éviter l'infestation
- [x] Modifier le PDF "auto traitement"
- [x] Modifier le PDF "préparer son domicile"

Tâches dev (à compléter sans doute): 
- [x] https://github.com/MTES-MCT/stop-punaises/issues/377
- [x] https://github.com/MTES-MCT/stop-punaises/issues/374
- [x] https://github.com/MTES-MCT/stop-punaises/issues/375
- [x] https://github.com/MTES-MCT/stop-punaises/issues/373
- [x] https://github.com/MTES-MCT/stop-punaises/issues/376
- [x] https://github.com/MTES-MCT/stop-punaises/issues/378
- [x] créer fixtures pour ERP et transports et faire la migration de l'entité Signalement pour prendre en compte ces types de signalement
- [x] Editer les PDF [dispo sur le drive](https://drive.google.com/drive/u/0/folders/1kyFwKVDLbqQbL_kdRj1YHxGyqhQNXdix)

**Comment by emilschn** [comment]
Pas grave si c'est pas tout à fait le même type de données entre ERP et transport ?

**Comment by mathildepoulpux** [comment]
Non, dans le listing y a une info qui va différer, la colonne "Nom" : 
- Pour les ERP : le nom de l'établissement
- Pour les transports : le type sélectionné (bus / métro / tram / train / autre)

Ca pose pas de pb ?

**Comment by emilschn** [comment]
Je posais surtout la question pour les données qui vont varier (dans un cas une adresse fixe, dans l'autre un numéro, un départ/destination, etc.)
Et aussi, sur quoi on filtre le moyen de transport quand on cherche via CP/filtre via territoire ?

**Comment by mathildepoulpux** [comment]
Il y a juste une ville de départ

**Comment by mathildepoulpux** [comment]
Aperçu du formulaire :
https://github.com/MTES-MCT/stop-punaises/assets/97226289/580bd61c-02f6-4c11-92bb-a3532d8496f8

Maquette dispo en ligne [par ici](https://xd.adobe.com/view/cd89c517-038e-41f2-a80f-dfa7f5be7df5-98da/)

**Comment by hmeneuvrier** [comment]
Tâche à ajouter : 

- créer fixtures pour ERP et transports et faire la migration de l'entité Signalement pour prendre en compte ces types de signalement
