### ISSUE TITLE
[Annuaire Entreprise] Détection Canine

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#372]
* Intégrer les entreprises manquantes 
* Distinguer dans l'annuaire la détection et l'intervention 

Liste entreprises de détection canine - toutes ces entreprises doivent apparaitre dans la partie détection uniquement
https://docs.google.com/spreadsheets/d/1xIwkayWnR0LuxIDy40BGA5m_u6Lzs5Aq/edit?usp=drive_link&ouid=103115680612514741617&rtpof=true&sd=true

**Comment by hmeneuvrier** [comment]
1.     séparer les entreprises de détection et d'intervention. 

-> Comme cela se traduit visuellement ? Ajout d'un filtre ? Une info en plus dans l'encart ? Deux listes distinctes ? 
on ajoute les informations dans l'encart et on créé un filtre
-> Toutes les entreprises qu'on a récupéré actuellement, elles sont quoi ? Elles font les deux ? 
elles font de l'intervention, sauf si elles sont répertoriées dans le fichier du ticket, alors elles font de la détection canine

2.     ajouter des entreprises de détection canines. 

-> Dans le fichier excel que tu as fourni, il y a plus d'informations que ce qu'on a (deuxième tel, email, et certaines sont "pour les pro uniquement"), on fait quoi de ces infos supplémentaires ? 
deuxième tel et mail on laisse tomber. L'info "pour les pros" on la rajoute en base
-> Je ne comprend pas comment elles sont réparties géographiquement. Nous on fonctionne par département, et une entreprise intervenant dans plusieurs département est dupliquée pour chaque département
chaque entreprise listée dans une région est considérée comme intervenant dans tous les départements de la région
-> ces entreprises, certaines existent déjà dans notre base (par exemple MK DetectionCanine, même si le nom actuellement est MK DETECTION CANINE PUNAISE DE LIT), est-ce que je pars du postulat que je peux juste ajouter le type détection ? (et laisser al zone d'intervention actuellement définie ?
oui
-> peut-être que certaines n'existent pas encore, si c'est le cas est-ce qu'elle ne font que de la détection ?
oui
-> Est-ce qu'il doit y avoir un type "détection canine" ou si il y a le type "détection" c'est que c'est de la détection canine
détection = détection canine

**Comment by hmeneuvrier** [comment]
TODO : 

- [ ] faire évoluer l'entité pour ajouter isIntervention, isDetectionCanine, isProOnly (3 booléens)
- [ ] dans la migration, attribuer les valeur 1, 0, 0 à ces 3 nouvelles informations
- [ ] faire évoluer le fichier excel pour le faire correspondre plus à nos besoins (renommer les entêtes, revoir la façon de faire la répartition géographique, s'assurer que les noms correspondent exactement à ceux qu'on a déjà en base)
- [ ] faire une commande qui parcourt ce fichier, si l'entreprise existe déjà lui mettre les bonnes valeurs pour isIntervention, isDetectionCanine, isProOnly (0, 1 et selon le fichier) (pour chaque occurence), et si l'entreprise n'existe pas la créer dans les départements adéquats.
- [ ] faire évoluer l'affichage de la page entreprises-labellisees pour ajouter les informations detection/intervention et "only pro" dans l'encart et pour créer un filtre
