### ISSUE TITLE
[BO] Socle technique ERP / transport

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/stop-punaises#377]
- MIse à jour de la table signalement
- Ajout de fixtures ERP et transport

**Comment by hmeneuvrier** [comment]
- `type` (logement, ERP ou transport)
- `punaises_viewed_at` (date et heure à laquelle les punaises ont été vu) ERP et Transport
- `type_place` (type d'ERP ou type de transport en faisant un enum qui a deux fonctions pour envoyer une partie de la liste pour les ERP et l'autre partie pour les transports)
- `is_place_averti`  (boolean pour ERP et pour transport)
- `autres_informations` (message? pour ERP et pour transport)
- `nom_declarant`
- `prenom_declarant` 
- `email_declarant`
