### ISSUE TITLE
[FO - Annuaire] Corse

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#434]
je saisis code postal corse sur staging punaises dans le logement
j ai le formulaire pour acceder a l annuaire
je valide
Message d erreur :Erreur lors de l ajout du signalement

Aussi dans le fichier excel base de donnees des entreprises, les entreprises corses n avaient pas de numéro de departement
je ne sais pas si elles sont bien referencees

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/arnau/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/arnau/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>
<!--table
	{mso-displayed-decimal-separator:"\,";
	mso-displayed-thousand-separator:" ";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Aptos Narrow", sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}

  | SUD HYGIENE | 8, Rue Paulin Colonna D’Istria 20137 PORTO   VECCHIO | https://www.sudhygienesystemes.fr | 04 95 70 15 64|
  | NUISIBLES ET COMPAGNIE | Immeuble Sainte Lucie La Tour Route De Ville - 20200 BASTIA | https://www.nuisiblesetcompagnie.com/ | 09 70 35 78 99| 
  | LOUIS MARENGO | 19 A Cuddata di i Noci 20135 Conca | 07 86 15 26 31| 
  | CISMONTE 3D | Quartier Pornetto 20214 ZILIA | 06 43 19 70 34| 
  | NUISIBLES ET COMPAGNIE | Immeuble Sainte Lucie La Tour Route De Ville - 20200 BASTIA | https://www.nuisiblesetcompagnie.com/ | 09 70 35 78 99| 
  | SUD HYGIENE | 8, Rue Paulin Colonna D’Istria 20137 PORTO VECCHIO | https://www.sudhygienesystemes.fr | 04 95 70 15 64|

**Comment by emilschn** [comment]
Code postal saisi : 20600

**Comment by emilschn** [comment]
Les entreprises corses sont référencées avec les zip 2A et 2B ; voir si ça pose souci.
Les territoires sont référencés avec les zip 2A et 2B aussi.
Il va falloir faire des cas particuliers
