### ISSUE TITLE
[Punaises - BO] Fiche signalement

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#44]
[Voir la maquette 🔗 ](https://xd.adobe.com/view/e8dc7a51-ae64-49a3-bda8-9ea816c79fe5-bd8f/screen/f61a0cd1-0c1c-4514-a9ab-f5dddbc7a972)
[Voir la microcopie 💬 ](https://docs.google.com/spreadsheets/d/1JeIJb1PKFHyAH6LIBxsH0HvYsGFw8KjN/edit#gid=344031466)

### En-tête
- Signalement [id]
- Label avec le niveau d'infestation
- Date de création du signalement
- Date d'intervention

### Onglet intervention
![BO - fiche signalement](https://user-images.githubusercontent.com/97226289/173369229-1c298707-dcfe-4621-8f6a-a329b5ba5bd9.png)

Titre + labels avec le type d'intervention
Si type d'intervention = les deux, on affiche 2 labels (diagnostic + traitement)

Deux cartes modifiable (cf. MTES-MCT/stop-punaises#56 )

#### Photos de la situation
Par défaut : aucune photo avec un message d'info
Pour chaque photo, 2 actions possibles : visualiser & supprimer

### Onglet logement
Deux cartes modifiables (cf. MTES-MCT/stop-punaises#56 )
![BO - fiche signalement – tab logement](https://user-images.githubusercontent.com/97226289/173369262-bf462434-b988-4f72-b651-f2a3a85f7ec0.png)

### Onglet document
cf. MTES-MCT/stop-punaises#61 
![BO - fiche signalement – tab documents](https://user-images.githubusercontent.com/97226289/173368891-84a63311-a116-48ba-a1f4-0e1f4328b39f.png)

**Comment by emilschn** [comment]
Ok pour la carte. Du coup, on remet les deux colonnes sur deux parties égales, et on met un bouton "Afficher la carte" ?
Tu as une idée d'où l'afficher ?

**Comment by mathildepoulpux** [comment]
Je le mettrais en dessous de la carte avec l'adresse
![image](https://user-images.githubusercontent.com/97226289/200274913-514cb52b-b63a-4ada-92f7-fc423c2ac80d.png)
