### ISSUE TITLE
[Accessibilité] Le site est compréhensible sans styles (sauf ERP et Transport)

### ISSUE THREAD

**Issue by numew** [MTES-MCT/stop-punaises#486]
→ Formulaires : Rien n'indique les champs obligatoires et les erreurs de validation sont non visible

http://localhost:8090/signalement/logement

http://localhost:8090/bo/signalements/ajout

**Comment by numew** [comment]
En fait les champs obligatoire sont visible via l'affichage de l'erreur par défaut, je ne sais pas si il y'a eu un changement ou si j'ai raté le truc quand j'ai crée le ticket mais j'ai pas l'impression qu'on ai besoin d'agir 
![san_style](https://github.com/MTES-MCT/stop-punaises/assets/7130780/4758ba54-4bf3-4bbd-bc8e-6a866bc5a111)

Dans ce cas ce sera identique pour le #530 et #531

**Comment by emilschn** [comment]
@mathildepoulpux tu pourrais faire des tests sur ce type de problématique ? :)

**Comment by mathildepoulpux** [comment]
Moi ça me paraît bien

**Comment by emilschn** [comment]
OK, fermons alors :)
