### ISSUE TITLE
[Accessibilité] Rendre certains liens plus explicites

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/stop-punaises#497]
- [x]  Sur toutes les pages, le lien vers l’accueil est trop verbeux : [[Accueil - Stop punaises - Ministère de la transition écologique et de la cohésion des territoires link](http://localhost:8090/information#0)](http://localhost:8090/information#0)
- [x]  http://localhost:8090/information —> 3 liens pas très explicites : 
- [[où se cachent les punaises de lit ? link](http://localhost:8090/information#6)](http://localhost:8090/information#6)
- [[où se cachent les punaises de lit ? link](http://localhost:8090/information#7)](http://localhost:8090/information#7)
- [[0806 706 806 link](http://localhost:8090/information#8)](http://localhost:8090/information#8)
- [x]  http://localhost:8090/contact —> [[0806 706 806 link](http://localhost:8090/contact#5)](http://localhost:8090/contact#5)
- [x]  http://localhost:8090/signalement/logement —> [[Retour link](http://localhost:8090/signalement/logement#5)](http://localhost:8090/signalement/logement#5)
- [x]  http://localhost:8090/signalement/transport —> idem
- [x]  http://localhost:8090/signalement/erp —> idem
- [x]  http://localhost:8090/ —> enlever > dans le lien [[> En savoir plus link](http://localhost:8090/#6)](http://localhost:8090/#6)
- [x]  http://localhost:8090/bo/historique —> Tous les liens vers les signalements s’appellent “Voir le signalement” il faudrait rajouter la date ou l’id…
- [x]  http://localhost:8090/bo/entreprises —> idem pour les entreprises “Voir l’entreprise” ajouter le nom de l’entreprise
- [x]  http://localhost:8090/bo/signalements —> idem “Voir le signalement”
- [x]  http://localhost:8090/entreprises-labellisees?code-postal=12000 —> Lien en double sur le titre de l’entreprise (avec juste le nom de l’entreprise) et sur le site web (avec juste “accéder au site web”) si on garde en double, peut-être mettre pour les deux “accéder au site web de Entreprise machin”) Le lien vers le numéro de téléphone est juste le numéro de téléphone, est-ce que ça suffit ?
- [x]  http://localhost:8090/bo/signalements/ajout# - Lien “Suivant >” pas très explicite

**Comment by hmeneuvrier** [comment]
https://www.notion.so/Chaque-page-contient-des-liens-d-acc-s-rapide-860acc266d1f413b8bb3df1adbae969e

**Comment by emilschn** [comment]
@hmeneuvrier je suis en train de regarder
- Header : on a appliqué ce qui est encouragé par le DSFR : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/en-tete 
- Informations : 
  - tu changerais comment le 1er ?
  - il faut changer le 2ème pour "comment éviter les punaises de lit ?" ou tu as une autre proposition ?
  - et le téléphone ? mettre un title ?
- boutons Retour des formulaire, tu as une proposition ?
- Lien Suivant, tu proposes quoi ? c'est un terme récurrent, non ?

@mathildepoulpux tu en penses quoi ? j'ai un peu peur qu'on en fasse "trop" :)

**Comment by hmeneuvrier** [comment]
Pour le header, alors ok. On est peut-être juste pas forcément lié au bon ministère :D Parce qu'on se demande un peu ce que ça fout sur une plateformem pour se débarrasser des punaises de lit "transition écologique" ou "cohésion des territoires" :D 


> * Informations : **_[edit : ah oui, il n'y a pas de title]_**
>   
>   * tu changerais comment le 1er ?
Non en fait c'est bien

>   * il faut changer le 2ème pour "comment éviter les punaises de lit ?" ou tu as une autre proposition ? 
Très bien

>   * et le téléphone ? mettre un title ?
Je ne sais pas ce que c'est exactement ce numéro de téléphone, mais mettre un petit titre genre "Le réseau des ADIL répond à vos question au [0806 706 806](tel:+33806706806)"

> 
> * boutons Retour des formulaire, tu as une proposition ?
"Retour au choix de signalement" ?


> * Lien Suivant, tu proposes quoi ? c'est un terme récurrent, non ?
"Ajouter les détails de l'intervention" ? "Continuer l'ajout de signalement" ? "Etape suivante du formulaire" ?
