### ISSUE TITLE
[Accessibilité - Audit] [Suivi usager - 9.1] Titre mal appliqué

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/stop-punaises#647]
## Description
"Bonjour [prénom]," ne devrait pas être le titre de niveau 1 de cette page.

## Recommandation
Modifier la hiérarchie des titres. De :

    1. Bonjour Yaacov,
        2. Votre signalement #2024-44
            3. Signalement déposé
            3. Info du signalement
            3. Détails des événements
                4. Signalement transféré
                4. Signalement déposé
                4. Protocole envoyé

à (par exemple) :

    1. Suivi de votre signalement #2024-44
        2. Étape 1 sur 4 : Signalement déposé
        2. Info du signalement
        2. Détails des événements
            3. 12/02/2024 : Signalement transféré
            3. 11/02/2024 : Signalement déposé
            3. 11/02/2024 : Protocole envoyé

**Comment by hmeneuvrier** [comment]
en attente https://mattermost.incubateur.net/betagouv/pl/ugp1mafz5pnu7b7j6ir3eqk6he
