### ISSUE TITLE
Passage de beta.gouv.fr à gouv.fr

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/stop-punaises#741]
@sfinx13 @hmeneuvrier @numew 
Quelques notes de choses à faire pour le passage en gouv.fr
- changer les adresses e-mail 
  - dans les variables d'environnement
  - dans le fichier de conf de workflow
- liens dans CONTRIBUTING.md et README.md
- modification du fichier accessibilité et index

**Comment by emilschn** [comment]
@sfinx13 @hmeneuvrier @numew 
Quelques notes de choses à faire pour le passage en gouv.fr
- changer les adresses e-mail 
  - dans les variables d'environnement
  - dans le fichier de conf de workflow
- liens dans CONTRIBUTING.md et README.md
- modification du fichier accessibilité et index
