### ISSUE TITLE
[Sécurité - ANSSI] Mettre en place la déconnexion automatique des sessions d'accès après une durée déterminée

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/stop-punaises#749]
Configurer le service afin d'activer la déconnexion automatique des sessions des administrateurs et des utilisateurs inactifs après une durée déterminée.
Cette mesure vise à limiter le risque d'utilisation, par une personne malveillante, du compte d'un utilisateur, qui aurait laissé son équipement non verrouillé sans surveillance et ne se serait pas déconnecté du service.

**Comment by sfinx13** [comment]
C'est déjà fait via ces deux tickets :
* https://github.com/MTES-MCT/stop-punaises/issues/639
* https://github.com/MTES-MCT/stop-punaises/issues/482
