### ISSUE TITLE
[Données Entreprises] Importer historiques

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#753]
Dossiers avec tous les fichiers à importer (133 fichiers d entreprises)
https://drive.google.com/drive/u/0/folders/18pePTs01em2P4JAQwU9M7v7CL3XJXyBR

**Comment by emilschn** [comment]
Travail en cours...

- [ ] Intégrer l'uuid des entreprises à tous les tableaux
- [ ] Réunir dans un seul tableau en vérifiant le format
- [ ] Importer le fichier global

**Comment by arnaudchouk** [comment]
A priori erreur à l import, 
les signalements sont crees à la date d import au lieu de prendre la date d intervention comme date de creation
rejouer l import pour dater tous ces signalements à leur date d intervention

**Comment by emilschn** [comment]
J'ai ouvert un autre ticket ici : https://github.com/MTES-MCT/stop-punaises/issues/819
