### ISSUE TITLE
[BO - Listing signalements] Ajout de filtres

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/stop-punaises#76]
Ajout de filtres pour la liste des signalements 

Pour l'admin & l'entreprise : 
- Par type de signalement
- Par statut

En fonction des info dispo pour chaque rôle (cf. #75 )

**Comment by emilschn** [comment]
@mathildepoulpux c'est quoi un type de signalement ? et c'est quoi un statut ? :)
Vraies questions : je ne sais pas à quoi ça correspond !
