### ISSUE TITLE
[FO - Formulaire usagers] - Informations complémentaires

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#81]
Ajouter les champs suivants :
Statut : Proprietaire/Locataire
nom du bailleur/propriétaire
logement social : oui / non
allocation : oui /non
numéro d'allocataire (si oui à la précédente)

**Comment by emilschn** [comment]
@mathildepoulpux tu pourras me dire où tu les envisages ? :)

**Comment by mathildepoulpux** [comment]
Entre l'écran "Je vis dans..." et l'écran "Je pense avoir un problème de punaises depuis..."
https://user-images.githubusercontent.com/97226289/203361665-82ba83e2-1bc9-47dc-9b07-d9e5ada56058.mp4

J'ai mis la maquette à jour : https://xd.adobe.com/view/103ca18f-a36a-4e42-820a-831a2f5a67d1-456f/screen/2e62d63f-95c5-4384-a73a-a2bdc4fc5e51/

Nom du bailleur -> à afficher si l'usager coche "locataire"
Numéro d'allocataire -> à afficher si l'usager coche "oui" pour la question allocation

**Comment by arnaudchouk** [comment]
Ok pour moi :)
