### ISSUE TITLE
[Données entreprises] Corriger l'import historique

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/stop-punaises#819]
Problème de date lors de l'import https://github.com/MTES-MCT/stop-punaises/issues/753

**Comment by hmeneuvrier** [comment]
SELECT COUNT(id) FROM `signalement` WHERE `created_at` LIKE '2024-06-14%';
+-----------+
| COUNT(id) |
+-----------+
|      1075 |
+-----------+
