### ISSUE TITLE
[FO Usager] Partie Recommandation

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/stop-punaises#93]
En cas de niveau estimé d'infestation à 0 - j'ai répondu non à toutes les questions sur les punaises
Le texte indique : nous vous recommandons de transmettre votre signalement à un pro
Or dans un cas d'infestation nulle cela ne devrait pas être proposé

**Comment by emilschn** [comment]
Je me suis fait la remarque.
Mais à 0, il n'y a pas d'auto-traitement non plus ?
En fait, il faudrait peut être juste changer complètement l'écran si on est à 0 @mathildepoulpux  ?

**Comment by arnaudchouk** [comment]
la question est pourquoi la personne vient sur stop-punaises et a 0 ?
potentiellement d autres insectes --> recommander de s adresser à des spécialistes d autres problèmes + possibilité d envoyer le guide des bonnes pratiques pour éviter les infestations + protocole auto traitement si jamais il veut etre pro actif

**Comment by emilschn** [comment]
Rediriger vers Histologe si nécessaire ?

**Comment by arnaudchouk** [comment]
pas bete - mais il faudrait lister les cas dans lesquels les partenaires peuvent prendre en charge les nuisibles ?

**Comment by mathildepoulpux** [comment]
Je pense qu'à 0 on peut laisser le choix : 
- déposer son signalement sur Histologe
- recevoir quand même le protocole d'auto-traitement (si l'usager le veut à tout prix, y a pas trop de raison qu'on l'en empêche non ?)

**Comment by emilschn** [comment]
Si je résume : à modifier si 0 : 
- suppression phrase "Nous vous recommandons de transmettre votre signalement à un professionnel ..."
- reformulation "Toutefois, vous pouvez tenter de traiter le problème par vous-mêmes en suivant notre protocole."
- => proposition ? "Si vous le souhaitez, nous pouvons vous faire parvenir le protocole d'auto-traitement par email."
- suppression bouton "Prise en charge professionnelle"
- reformulation bouton "Prise en charge d'auto-traitement"
- => proposition ? "Recevoir le protocole d'auto-traitement"
- ajout d'un lien pour aller sur Histologe
- => proposition ? "Si vous rencontrez d'autres problèmes avec votre logement, n'hésitez pas à les signaler sur la plateforme **Histologe**"
